name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      # Pack the silero dir as a zip and upload to the release
      - name: ZIP Silero Dir
        run: |
          cd ${{ github.workspace }}/custom_components/silero
          zip silero.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/silero/silero.zip
          asset_name: silero.zip
          tag: ${{ github.ref }}
          overwrite: true
